name: Build
on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions: { contents: read }
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Check code
        run: npm install && npm run check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build distribution into dist/
        run: docker buildx build --output=type=local,dest=./dist .

      - name: Upload distribution
        uses: actions/upload-artifact@v7
        with:
          name: fh6-universal-radio
          path: dist/
